#!/bin/bash

source env.sh

start_env() {
	# uruchomienie python virtualenv
	if [ -d "$PROJECT_ENV" ]; then
		source $PROJECT_ENV/bin/activate
	else
		echo "Środowisko virtualenv nie uruchomione! Uruchom $0 env_init"
	fi
}

case $1 in
  "env")
    start_env
    /bin/bash -c ". $PROJECT_ENV/bin/activate; exec /bin/bash --norc -i"
    ;;

  "env_init")
    python3 -m venv $PROJECT_ENV
    start_env
    python3 -m pip install -r docs/requirements.txt
    ;;

  'manage')
    start_env
    python3 manage.py $2
    ;;

  'start')
    start_env
    python3 manage.py runserver
    ;;

  *)
    echo "Użycie:"
		echo -e "$0 start${NC} - uruchomienie aplikacji django"
		echo -e "$0 manage${NC} - komendy django"
		echo -e "$0 env${NC} - aktywacja virtualenv"
		echo -e "$0 env_init${NC} - inicjalizacja srodowiska virtualenv"
    ;;
esac
